# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a14741a8561a1e5b20af1d31d5086315b5ec16c5519f43b9e0bd40500aa9edbad8e3e37fe92fc672ab2a21720994df29cce19beab87940a5e0a7e581f512b96

test:
  secret_key_base: b776b30195dcf464d97347cb1590ed126597067f57ed77bd88ad54641bbd84d8a89957d808dd5d8c3df361d6b5ee783006fae3a1af491f24cb327be4de116c37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
